import { BLCodeAndTrans } from "./common";

export type BLAndTransAuth = {
    LOGIN_SUCCESS: BLCodeAndTrans;
    LOGOUT_SUCCESS: BLCodeAndTrans;
    LOGOUT_FAILED: BLCodeAndTrans;
    GET_SESSION_SUCCESS: BLCodeAndTrans;
    SESSION_NOT_EXIST: BLCodeAndTrans;
    INCORRECT_EMAIL_OR_PASSWORD: BLCodeAndTrans;
    ACCESS_TOKEN_EXPIRED: BLCodeAndTrans;
    ACCESS_TOKEN_MALFORMED: BLCodeAndTrans;
    ACCESS_TOKEN_NOT_BEFORE: BLCodeAndTrans;
    ACCESS_TOKEN_VERIFY_UNKNOWN: BLCodeAndTrans;
    ACCESS_TOKEN_NOT_PROVIDED: BLCodeAndTrans;
    REISSUE_ACCESS_TOKEN_FAILED: BLCodeAndTrans;
    INAPPROPRIATE_REFRESH_TOKEN: BLCodeAndTrans;
    REFRESH_TOKEN_EXPIRED: BLCodeAndTrans;
    REFRESH_ACCESS_TOKEN_SUCCESS: BLCodeAndTrans;
    INAPPROPRIATE_ACCESS_TOKEN: BLCodeAndTrans;
    REFRESH_TOKEN_MALFORMED: BLCodeAndTrans;
    REFRESH_TOKEN_NOT_BEFORE: BLCodeAndTrans;
    REFRESH_TOKEN_VERIFY_UNKNOWN: BLCodeAndTrans;
    AUTH_FORMAT_ERROR_ACCESS_TOKEN: BLCodeAndTrans;
    UNKNOWN_AUTH_ERROR: BLCodeAndTrans;
    REFRESH_TOKEN_NOT_PROVIDED: BLCodeAndTrans;
    CAN_NOT_UPDATE_REFRESH_TOKEN: BLCodeAndTrans;
};
