services:
  bunny-rest-dev:
    image: bunny-rest-dev-image
    container_name: bunny-rest-dev
    build:
      context: ./
      args:
        PKG_INSTALL_ENV: development
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./:/bunny-rest:ro
      - /bunny-rest/node_modules
    env_file:
      - .env.development
    command: yarn dev
    expose:
      - "8080"
      - "9090"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_dev
      - MONGO_INITDB_ROOT_PASSWORD=root_dev_password
    volumes:
      - mongo-dev:/data/db

  redis:
    image: redis
    container_name: redis-dev

volumes:
  mongo-dev:
