version: '3.7'
services:

  postgres-dev:
    image: postgres
    container_name: postgres-dev
    environment:
      - POSTGRES_PASSWORD=root_dev_password
      - POSTGRES_DB=bunny_rest_dev
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-dev:/var/lib/postgresql/data

  mongo-dev:
    image: mongo
    container_name: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_dev
      - MONGO_INITDB_ROOT_PASSWORD=root_dev_password
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-dev:/data/db

  redis-dev:
    image: redis
    container_name: redis-dev
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis-dev:/data


volumes:
  postgres-dev:
  mongo-dev:
  redis-dev:
