version: '3.7'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-dev
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bunny-rest-dev

  bunny-rest-dev:
    image: bunny-rest-dev
    build:
      context: ./
      args:
        PKG_INSTALL_ENV: development
    volumes:
      - ./:/bunny-rest:ro
      - /bunny-rest/node_modules
    environment:
      - PORT=8080
      - MONGO_DB_URI=mongodb://root_dev:root_dev_password@mongo:27017/bunny-rest?authSource=admin
      - SALT_WORK_FACTOR=10
      - ACCESS_TOKEN_TTL=0.5m
      - REFRESH_TOKEN_TTL=1y
      - METRICS_PORT=9090
      - REDIS_URI=redis://@redis:6379
    command: yarn dev
    expose:
      - "8080"
      - "9090"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_dev
      - MONGO_INITDB_ROOT_PASSWORD=root_dev_password
    volumes:
      - mongo-dev:/data/db

  redis:
    image: redis
    container_name: redis-dev

volumes:
  mongo-dev:
